name: "FRP Client"
description: "You can use this tool to achieve remote access to local Home Assistant OS by port forwarding"
url: https://github.com/libnewton/hass-addon-frp-client
version: "1.0.8"
slug: "frp_client"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - "share:rw"
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  serverAddr: "example.com"
  serverPort: 7000
  authToken: "123456789"
  webServerPort: 7500
  webServerUser: "admin"
  webServerPassword: "123456789"
  customDomain: "example.com"
  proxyName: "homeassistant"
  # Use the pipe symbol | to indicate multiline defaults, 
  # this helps the UI understand it's a block
  frpc_toml_content: |
    # Paste your frpc.toml here
  frp_token_content: |
    # file content
  frp_ca_crt_content: |
    # file
  frp_client_crt_content: |
    # file
  frp_client_key_content: |
    # file
schema:
  serverAddr: str
  serverPort: int
  authToken: str
  webServerPort: int
  webServerUser: str
  webServerPassword: str
  customDomain: str
  proxyName: str
  # Note: There is no 'textarea' type; 'str?' is the standard way.
  frpc_toml_content: str?
  frp_token_content: str?
  frp_ca_crt_content: str?
  frp_client_crt_content: str?
  frp_client_key_content: str?
